// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v5.26.1
// source: posts.proto

/* eslint-disable */
import { Observable } from "rxjs";

export interface ListRequest {
}

export interface ListResponse {
  data: ListResponse_Data[];
}

export interface ListResponse_Data {
  id: string;
  title: string;
  content: string;
  author: string;
}

export interface CreateRequest {
  title: string;
  content: string;
  author: string;
}

export interface CreateResponse {
  id: string;
  title: string;
  content: string;
  author: string;
}

export interface GetRequest {
  id: string;
}

export interface GetResponse {
  id: string;
  title: string;
  content: string;
  author: string;
}

export interface UpdateRequest {
  id: string;
  title?: string | undefined;
  content?: string | undefined;
  author?: string | undefined;
}

export interface UpdateResponse {
  id: string;
  title: string;
  content: string;
  author: string;
}

export interface DeleteRequest {
  id: string;
}

export interface DeleteResponse {
}

export interface Post {
  list(request: ListRequest): Observable<ListResponse>;
  create(request: CreateRequest): Observable<CreateResponse>;
  get(request: GetRequest): Observable<GetResponse>;
  update(request: UpdateRequest): Observable<UpdateResponse>;
  delete(request: DeleteRequest): Observable<DeleteResponse>;
}
