---
- name: Save MicroK8s Config to Local kubeconfig
  hosts: control_plane
  become: true
  gather_facts: false
  tasks:
    - name: Create variable from command
      command: "microk8s config"
      register: microk8s_config_output

    - name: Execute microk8s config command
      set_fact:
        microk8s_config: "{{ microk8s_config_output.stdout }}"

    - name: Extract current server URL
      set_fact:
        current_server: "{{ microk8s_config | from_yaml | json_query('clusters[0].cluster.server') }}"

    - name: Extract current server IP address and port
      set_fact:
        current_ip: "{{ current_server.split('//')[1].split(':')[0] }}"
        current_port: "{{ current_server.split('//')[1].split(':')[1] }}"

    - name: Replace the server IP address in the Kubernetes config
      set_fact:
        updated_kubeconfig: "{{ microk8s_config | regex_replace('server: https://'+current_ip+':'+current_port, 'server: https://'+ ansible_host +':'+ current_port) }}"

    - name: Write microk8s config to temporary file
      copy:
        content: "{{ updated_kubeconfig }}"
        dest: /tmp/microk8s_kubeconfig

    - name: Fetch microk8s config to local machine
      fetch:
        src: /tmp/microk8s_kubeconfig
        dest: ./microk8s_kubeconfig
        flat: yes

    - name: Clean up temporary kubeconfig file on control plane
      file:
        path: /tmp/microk8s_kubeconfig
        state: absent

- name: Rename fetched kubeconfig file locally
  hosts: localhost
  tasks:
    - name: Rename microk8s_kubeconfig to kubeconfig
      command: mv ./microk8s_kubeconfig ../config.yaml
