name: Blog with microservice Docker CI

on:
  push:
    branches:
      - main
    paths:
      - golang/blog-with-microservice/**

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push auth image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/golang/blog-with-microservice/auth
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/struckchure/recipe/blog-with-micro-auth:latest

      - name: Build and push posts image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/golang/blog-with-microservice/posts
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/struckchure/recipe/blog-with-micro-posts:latest

      - name: Build and push gateway image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/golang/blog-with-microservice/gateway
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/struckchure/recipe/blog-with-micro-gateway:latest
